/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrabajosRouteImport } from './routes/trabajos'
import { Route as PaginaWebMalagaRouteImport } from './routes/pagina-web-malaga'
import { Route as ConseguirClientesMalagaRouteImport } from './routes/conseguir-clientes-malaga'
import { Route as ComoConseguirClientesNegocioRouteImport } from './routes/como-conseguir-clientes-negocio'
import { Route as IndexRouteImport } from './routes/index'

const TrabajosRoute = TrabajosRouteImport.update({
  id: '/trabajos',
  path: '/trabajos',
  getParentRoute: () => rootRouteImport,
} as any)
const PaginaWebMalagaRoute = PaginaWebMalagaRouteImport.update({
  id: '/pagina-web-malaga',
  path: '/pagina-web-malaga',
  getParentRoute: () => rootRouteImport,
} as any)
const ConseguirClientesMalagaRoute = ConseguirClientesMalagaRouteImport.update({
  id: '/conseguir-clientes-malaga',
  path: '/conseguir-clientes-malaga',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoConseguirClientesNegocioRoute =
  ComoConseguirClientesNegocioRouteImport.update({
    id: '/como-conseguir-clientes-negocio',
    path: '/como-conseguir-clientes-negocio',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-conseguir-clientes-negocio': typeof ComoConseguirClientesNegocioRoute
  '/conseguir-clientes-malaga': typeof ConseguirClientesMalagaRoute
  '/pagina-web-malaga': typeof PaginaWebMalagaRoute
  '/trabajos': typeof TrabajosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-conseguir-clientes-negocio': typeof ComoConseguirClientesNegocioRoute
  '/conseguir-clientes-malaga': typeof ConseguirClientesMalagaRoute
  '/pagina-web-malaga': typeof PaginaWebMalagaRoute
  '/trabajos': typeof TrabajosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-conseguir-clientes-negocio': typeof ComoConseguirClientesNegocioRoute
  '/conseguir-clientes-malaga': typeof ConseguirClientesMalagaRoute
  '/pagina-web-malaga': typeof PaginaWebMalagaRoute
  '/trabajos': typeof TrabajosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-conseguir-clientes-negocio'
    | '/conseguir-clientes-malaga'
    | '/pagina-web-malaga'
    | '/trabajos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-conseguir-clientes-negocio'
    | '/conseguir-clientes-malaga'
    | '/pagina-web-malaga'
    | '/trabajos'
  id:
    | '__root__'
    | '/'
    | '/como-conseguir-clientes-negocio'
    | '/conseguir-clientes-malaga'
    | '/pagina-web-malaga'
    | '/trabajos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoConseguirClientesNegocioRoute: typeof ComoConseguirClientesNegocioRoute
  ConseguirClientesMalagaRoute: typeof ConseguirClientesMalagaRoute
  PaginaWebMalagaRoute: typeof PaginaWebMalagaRoute
  TrabajosRoute: typeof TrabajosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trabajos': {
      id: '/trabajos'
      path: '/trabajos'
      fullPath: '/trabajos'
      preLoaderRoute: typeof TrabajosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagina-web-malaga': {
      id: '/pagina-web-malaga'
      path: '/pagina-web-malaga'
      fullPath: '/pagina-web-malaga'
      preLoaderRoute: typeof PaginaWebMalagaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseguir-clientes-malaga': {
      id: '/conseguir-clientes-malaga'
      path: '/conseguir-clientes-malaga'
      fullPath: '/conseguir-clientes-malaga'
      preLoaderRoute: typeof ConseguirClientesMalagaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-conseguir-clientes-negocio': {
      id: '/como-conseguir-clientes-negocio'
      path: '/como-conseguir-clientes-negocio'
      fullPath: '/como-conseguir-clientes-negocio'
      preLoaderRoute: typeof ComoConseguirClientesNegocioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoConseguirClientesNegocioRoute: ComoConseguirClientesNegocioRoute,
  ConseguirClientesMalagaRoute: ConseguirClientesMalagaRoute,
  PaginaWebMalagaRoute: PaginaWebMalagaRoute,
  TrabajosRoute: TrabajosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
